### ISSUE TITLE
Use loop to install php module on Ubuntu

### ISSUE THREAD

**Issue by chendelin1982** [websoft9dev/role_php-fpm#3]
The same with the following task
```
  - name: Install php_modules_common for {{ansible_distribution}}, print when all module installation errors but installation go on
    yum: 
      name: "{{ item }}"
      state: latest
      update_cache: yes
    register: php_install_result
    failed_when: False
    loop: "{{ php_modules_common }}"
```

**Comment by qiaofeng1227** [comment]
```
- name: Install php_modules_common
  apt:
    name: "{{ item | regex_replace('-', php_version~'-') }}"
    state: latest
    update_cache: yes
  failed_when: False
  loop: "{{ php_modules_common }}"
  
- name: Install php_extra_modules_ubuntu
  apt:
    name: "{{ item | regex_replace('-', php_version~'-') }}"
    state: latest
    update_cache: yes
  failed_when: False
  loop: "{{ php_extra_modules_ubuntu }}"
```
Done
